# Hugo configuration file
baseURL = 'https://ravleenbajaj.github.io/'
title = 'Ravleen Bajaj'

# Language settings
defaultContentLanguage = 'en'
hasCJKLanguage = false
defaultContentLanguageInSubdir = false
removePathAccents = true

# Build settings
paginate = 10
enableEmoji = true
enableRobotsTXT = true
canonifyURLs = false
disableAliases = true
summaryLength = 30

# Hugo Blox Builder
module:
  imports:
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-starter"

# Site parameters
[params]
  # Site header
  main_menu = {enable = true, align = "l", show_logo = true, show_language = false, show_day_night = true, show_search = true, highlight_active_link = true}

  # Localization
  date_format = "Jan 2, 2006"
  time_format = "3:04 PM"

  # Contact details
  email = "your.email@example.com"
  phone = "555 555 5555"

  # Regional settings
  region = "US"

  # Site features
  highlight = true
  highlight_languages = ["r"]
  math = false
  diagram = false
  privacy_pack = false
  edit_page = {repo_url = "https://github.com/ravleenbajaj/ravleenbajaj.github.io", content_dir = "content", repo_branch = "main", editable = {page = false, post = false, book = false}}
  show_related = {book = true, page = false, post = true, project = true, publication = true, event = true}

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"

# Related content
[related]
  threshold = 80
  includeNewer = true
  toLower = true
  [[related.indices]]
    name = "title"
    weight = 60
  [[related.indices]]
    name = "summary"
    weight = 50
  [[related.indices]]
    name = "tags"
    weight = 80
  [[related.indices]]
    name = "categories"
    weight = 70

# Markup settings
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

# Security settings
[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
  [security.funcs]
    getenv = ['^HUGO_']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']