# Hugo configuration file
title: "Your Name - Resume"
baseURL: "https://ravleenbajaj.github.io/"
languageCode: "en-us"
defaultContentLanguage: "en"

# Hugo Blox Builder Configuration
module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-reveal

# Site parameters
params:
  # Theme
  appearance:
    theme_day: minimal
    theme_night: minimal
    font: minimal
    font_size: L
  
  # Contact details
  email: your.email@example.com
  phone: "+1 234 567 8901"
  
  # Social media
  profiles:
    - icon: at-symbol
      url: "mailto:your.email@example.com"
      label: E-mail Me
    - icon: brands/linkedin
      url: https://www.linkedin.com/in/yourprofile
    - icon: brands/github
      url: https://github.com/ravleenbajaj

# Navigation
menu:
  main:
    - name: Home
      url: '#about'
      weight: 10
    - name: Experience
      url: '#experience'
      weight: 20
    - name: Education
      url: '#education'
      weight: 30
    - name: Skills
      url: '#skills'
      weight: 40
    - name: Contact
      url: '#contact'
      weight: 60

# Markup configuration
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    lineNos: false
    style: github
    lineNumbersInTable: false

# Hugo version
hugo:
  version: "0.120.4"

# Enable section
enableRobotsTXT: true
canonifyURLs: false
relativeURLs: false